services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: ptf_db        # Имя БД
      POSTGRES_USER: ptf_db_user # Имя пользователя
      POSTGRES_PASSWORD: "2354"  # Пароль
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    image: ghcr.io/${IMAGE_REPO:-k0ber/ptfbackend}:${IMAGE_TAG:-latest}
    container_name: ptf_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db               # Хост для БД - это имя сервиса 'db'
      DB_NAME: ptf_db           # Имя БД (совпадает с POSTGRES_DB)
      DB_USER: ptf_db_user
      DB_PASSWORD: "2354"

      JWT_SECRET: "IL0j3L34rnmqgKt-rWi%%1hJ0s3Li.u1sG_S4ndHyp3r9l"
      JWT_REALM: "KtorRealm"
      JWT_EXPIRATION_MS: 3600000
      JWT_ISSUER: "http://0.0.0.0:8080/"
      JWT_AUDIENCE: "ptf-users"

    restart: unless-stopped

volumes:
  postgres_data: