services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    image: ghcr.io/${IMAGE_REPO:-k0ber/ptfbackend}:${IMAGE_TAG:-latest}
    container_name: ptf_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=ptf_db
      - DB_USER
      - DB_PASSWORD

      - JWT_SECRET
      - JWT_REALM
      - JWT_EXPIRATION_MS
      - JWT_ISSUER
      - JWT_AUDIENCE

    restart: unless-stopped

volumes:
  postgres_data: