name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches: [ "main" ]

jobs:
  docker_and_deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ptf_backend:${{ github.sha }}
            ghcr.io/${{ github.repository }}/ptf_backend:latest

      - name: Deploy via SSH and Restart Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            export DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}"
            export DOCKER_PAT="${{ secrets.DOCKER_PAT }}"
            
            echo "Starting deployment on VDS..."
            
            PROJECT_DIR="/root/ptf-backend" 
            cd "$PROJECT_DIR"
            
            # TODO: DEBUG
            echo "DEBUG: DOCKER_USERNAME is: ${DOCKER_USERNAME}"
            
            # Авторизация в GHCR на VDS для скачивания образа
            echo "Authorizing Docker on VDS..."
            echo "${DOCKER_PAT}" | docker login ghcr.io -u "${DOCKER_USERNAME}" --password-stdin
            
            # Задаем переменные для docker-compose.yml
            export IMAGE_TAG="${{ github.sha }}"
            export IMAGE_REPO="${{ github.repository }}"
            
            echo "Pulling image: ghcr.io/$IMAGE_REPO/ptf_backend:$IMAGE_TAG"
            
            # Скачиваем новый образ и запускаем контейнеры
            docker compose pull app
            docker compose up -d
            
            # Очистка
            docker image prune -f
            
            echo "Deployment finished. Check logs for ptf_backend_app container."